server:
  port: 8888

app:
  api-prefix: /api/v1

#
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8000
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8001
          predicates:
          - Path=${app.api-prefix}/profile/user-profile/**
          filters:
          - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8006
          predicates:
            - Path=${app.api-prefix}/notifications/**
          filters:
            - StripPrefix=2

