server:
  port: 8001
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  datasource:
    url: "jdbc:mysql://localhost:3306/topic9_profile_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  spring:
    kafka:
      bootstrap-servers: localhost:9094
      consumer:
        group-id: profile-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"