server:
  port: 8001
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  datasource:
    url: "jdbc:mysql://localhost:3306/topic9_profile_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

