server:
    port: 8000
    servlet:
        context-path: /identity

spring:
    application:
        name: identity-service
    datasource:
        url: jdbc:mysql://mysql:3306/topic9_identity_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: kafka-broker:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            group-id: identity-service2
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds

app:
    services:
        profile: http://profile-service:8100/profile
