server:
    port: 8888

app:
    api-prefix: /api/v1
    identity-service-url: http://identity-service:8000/identity

#
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: identity_service
                  uri: http://identity-service:8000
                  predicates:
                      - Path=/api/v1/identity/**
                  filters:
                      - StripPrefix=2
                - id: profile_service
                  uri: http://profile-service:8100
                  predicates:
                      - Path=/api/v1/profile/user-profile/**
                  filters:
                      - StripPrefix=2
                - id: notification_service
                  uri: http://notification-service:8700
                  predicates:
                      - Path=/api/v1/notifications/**
                  filters:
                      - StripPrefix=2
                - id: order_service
                  uri: http://order-service:8300
                  predicates:
                      - Path=/api/v1/order/**
                  filters:
                      - StripPrefix=2
                - id: product_service
                  uri: http://product-service:8200
                  predicates:
                      - Path=/api/v1/product/**
                  filters:
                      - StripPrefix=2
                - id: payment_service
                  uri: http://payment-service:8500
                  predicates:
                      - Path=/api/v1/payment/**
                  filters:
                      - StripPrefix=2

                - id: customer_summary_service
                  uri: http://customer-summary-service:8800
                  predicates:
                      - Path=/api/v1/customer-summary/**
                  filters:
                      - StripPrefix=2
