server:
    port: 8889

app:
    api-prefix: /api/v1

#
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: identity_service
                  uri: http://localhost:8000
                  predicates:
                      - Path=${app.api-prefix}/identity/**
                  filters:
                      - StripPrefix=2
                - id: profile_service
                  uri: http://localhost:8001
                  predicates:
                      - Path=${app.api-prefix}/profile/user-profile/**
                  filters:
                      - StripPrefix=2
                - id: notification_service
                  uri: http://localhost:8007
                  predicates:
                      - Path=${app.api-prefix}/notifications/**
                  filters:
                      - StripPrefix=2
                - id: order_service
                  uri: http://localhost:8003
                  predicates:
                      - Path=${app.api-prefix}/order/**
                  filters:
                      - StripPrefix=2
                - id: product_service
                  uri: http://localhost:8002
                  predicates:
                      - Path=${app.api-prefix}/product/**
                  filters:
                      - StripPrefix=2
                - id: payment_service
                  uri: http://localhost:8005
                  predicates:
                      - Path=${app.api-prefix}/payment/**
                  filters:
                      - StripPrefix=2
                - id: shipping_service
                  uri: http://localhost:8006
                  predicates:
                      - Path=${app.api-prefix}/shipping/**
                  filters:
                      - StripPrefix=2

                - id: customer_summary_service
                  uri: http://localhost:8008
                  predicates:
                      - Path=${app.api-prefix}/customer-summary/**
                  filters:
                      - StripPrefix=2
